<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '16',
    'typeid' => '0',
    'title' => '天亮教育呼吁学生去省博物馆感受文化暑假',
    'style' => '',
    'thumb' => '',
    'keywords' => '天亮培优学校 博物馆 小学生',
    'description' => '我省各大博物为中小学生准备了内容丰富的系列文化大餐，天亮培优学校呼吁学生去湖北省博物馆，“穿越时空”回到汉唐，跟专业人士学古代“六艺”，感受文化暑假。',
    'posids' => '1',
    'url' => 'http://www.tianliangedu.com/2017/xiaoxue_0620/1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1497945682',
    'updatetime' => '1497953316',
    'hitsid' => 'c-1-1',
    'views' => '6',
    'yesterdayviews' => '0',
    'dayviews' => '6',
    'weekviews' => '6',
    'monthviews' => '6',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '16',
    'typeid' => '0',
    'title' => '“心灵关爱，童心护航”爱心义卖',
    'style' => '',
    'thumb' => 'http://www.tianliangedu.com/uploadfile/2017/0706/20170706023421406.jpg',
    'keywords' => '童心 爱心 天亮教育',
    'description' => '天门市实验小学举办“心灵关爱，童心护航”爱心义卖活动',
    'posids' => '0',
    'url' => 'http://www.tianliangedu.com/2017/xiaoxue_0706/2.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'tianliangedu',
    'inputtime' => '1499322729',
    'updatetime' => '1499322850',
    'hitsid' => 'c-1-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '16',
    'typeid' => '0',
    'title' => '起跑线上的恐慌：5岁学英语被告知晚了',
    'style' => '',
    'thumb' => 'http://www.tianliangedu.com/uploadfile/2017/0713/20170713122706280.jpg',
    'keywords' => '起跑线 学英语',
    'description' => '学校的大门，像是一把重新丈量这个社会的尺子。那些来自形形色色的，或富有、或贫穷家庭的孩子们，迈进那道大门，穿上清一色校服，一切便清   ',
    'posids' => '1',
    'url' => 'http://www.tianliangedu.com/2017/xiaoxue_0706/3.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'tianliangedu',
    'inputtime' => '1499324405',
    'updatetime' => '1499324619',
    'hitsid' => 'c-1-3',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '16',
    'typeid' => '0',
    'title' => '小学班主任用成语写评语 内含学生姓名',
    'style' => '',
    'thumb' => 'http://www.tianliangedu.com/uploadfile/2017/0710/20170710110112980.jpg',
    'keywords' => '评语 教师 照片',
    'description' => '武汉天亮教育发布网络上走红的班主任写给学生的评语，四字短评包含学生姓名和老师评价，彰显才情与创意。',
    'posids' => '0',
    'url' => 'http://www.tianliangedu.com/2017/xiaoxue_0710/4.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'tianliangedu',
    'inputtime' => '1499655553',
    'updatetime' => '1499656085',
    'hitsid' => 'c-1-4',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '16',
    'typeid' => '0',
    'title' => '我们是如何将学生培养为精致的利己主义者的？',
    'style' => '',
    'thumb' => 'http://www.tianliangedu.com/uploadfile/2017/0718/20170718024954538.png',
    'keywords' => '天亮教育 学生培养 主义者',
    'description' => '天亮教育发布，钱理群先生曾经提出一个“精致的利己主义者”的概念，说在实用主义、功利主义、虚无主义的教育背景下，我们正在培养出一批“绝对的、精致的利己主义者”。',
    'posids' => '1',
    'url' => 'http://www.tianliangedu.com/2017/xiaoxue_0718/5.html',
    'listorder' => '4',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1500360286',
    'updatetime' => '1500360594',
    'hitsid' => 'c-1-5',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>