<?php
return array (
  4 => 
  array (
    'id' => '4',
    'catid' => '17',
    'typeid' => '0',
    'title' => '今秋武汉小学初中划片公布',
    'style' => '',
    'thumb' => '',
    'keywords' => '武汉 天亮 小学 初中',
    'description' => '今秋武汉小学初中划片公布 ，中小学对口仍以单校划片为主。',
    'posids' => '1',
    'url' => 'https://www.tianliangedu.com/2017/chuzhong_0620/4.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1497950342',
    'updatetime' => '1498049452',
    'hitsid' => 'c-13-4',
    'views' => '4',
    'yesterdayviews' => '2',
    'dayviews' => '2',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  15 => 
  array (
    'id' => '15',
    'catid' => '17',
    'typeid' => '0',
    'title' => '天亮教育发布特优教师专业引领',
    'style' => '',
    'thumb' => 'https://www.tianliangedu.com/uploadfile/2017/0712/20170712105731281.jpg',
    'keywords' => '教师 专业 天亮教育',
    'description' => '武昌区中小学新教师成长的必由之路为了使新教师尽快适应武昌区教育发展的需要，进一步增强新教师职业意识，巩固专业思想，更好地掌握教育教',
    'posids' => '0',
    'url' => 'https://www.tianliangedu.com/2017/chuzhong_0712/15.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'tianliangedu',
    'inputtime' => '1499827980',
    'updatetime' => '1499828251',
    'hitsid' => 'c-13-15',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  17 => 
  array (
    'id' => '17',
    'catid' => '17',
    'typeid' => '0',
    'title' => '天亮家长必读：初三生最需要听的五句话',
    'style' => '',
    'thumb' => 'https://www.tianliangedu.com/uploadfile/2017/0713/20170713124313942.png',
    'keywords' => '天亮教育 初三 家长',
    'description' => '优秀是一种习惯，只有知道如何停止的人才知道如何加快速度。',
    'posids' => '0',
    'url' => 'https://www.tianliangedu.com/2017/chuzhong_0713/17.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'tianliangedu',
    'inputtime' => '1499920923',
    'updatetime' => '1499921289',
    'hitsid' => 'c-13-17',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  20 => 
  array (
    'id' => '20',
    'catid' => '17',
    'typeid' => '0',
    'title' => '家长，教育孩子的路上，您不愿与老师并肩，又能相信谁?',
    'style' => '',
    'thumb' => 'https://www.tianliangedu.com/uploadfile/2017/0716/20170716080008887.jpg',
    'keywords' => '家长 老师 孩子',
    'description' => '家长，教育孩子的路上，您不愿与老师并肩，又能相信谁?老师和家长是可以团结与协作起来的，也只有让家校和谐，才能让学生真正受益！',
    'posids' => '1',
    'url' => 'https://www.tianliangedu.com/2017/chuzhong_0716/20.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1500206275',
    'updatetime' => '1500206407',
    'hitsid' => 'c-13-20',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>