<?php
return array (
  3 => 
  array (
    'id' => '3',
    'catid' => '21',
    'typeid' => '0',
    'title' => '教育部：义务教育语文、历史等教学必须使用规定教材',
    'style' => '',
    'thumb' => 'http://bxu2359560426.my3w.com/uploadfile/2017/0620/20170620125444384.jpg',
    'keywords' => '天亮教育 教育部',
    'description' => '为做好义务教育阶段的道德与法治、语文、历史和小学科学教学用书工作，教育部公示义务教育语文、历史等教学必须使用规定教材。',
    'posids' => '0',
    'url' => 'https://www.tianliangedu.com/2017/latest_0620/3.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1497949013',
    'updatetime' => '1498038050',
    'hitsid' => 'c-13-3',
    'views' => '7',
    'yesterdayviews' => '4',
    'dayviews' => '3',
    'weekviews' => '7',
    'monthviews' => '7',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '21',
    'typeid' => '0',
    'title' => '天亮教育热烈庆祝中国共产党成立九十六周年',
    'style' => '',
    'thumb' => 'https://www.tianliangedu.com/uploadfile/2017/0713/20170713123430952.jpg',
    'keywords' => '天亮 共产党 九十六周年',
    'description' => '永葆共产党人的奋斗精神——热烈庆祝中国共产党成立九十六周年，天亮教育发布人民日报社论。',
    'posids' => '1',
    'url' => 'https://www.tianliangedu.com/2017/latest_0621/6.html',
    'listorder' => '1',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1498035940',
    'updatetime' => '1498036039',
    'hitsid' => 'c-13-6',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '21',
    'typeid' => '0',
    'title' => '学生家长呼吁不要把“新中考”变成小高考',
    'style' => '',
    'thumb' => 'https://www.tianliangedu.com/uploadfile/2017/0713/20170713123832762.jpg',
    'keywords' => '天亮教育 新中考 高考',
    'description' => '2017年之前，语文、数学、英语、物理、化学、体育6门，共580分。而新中考实行“3必考+3选考+体育”的模式。',
    'posids' => '1',
    'url' => 'https://www.tianliangedu.com/2017/latest_0621/7.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1498036295',
    'updatetime' => '1498037261',
    'hitsid' => 'c-13-7',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  10 => 
  array (
    'id' => '10',
    'catid' => '21',
    'typeid' => '0',
    'title' => '起跑线上的恐慌：5岁学英语被告知晚了',
    'style' => '',
    'thumb' => 'https://www.tianliangedu.com/uploadfile/2017/0713/20170713122814257.jpg',
    'keywords' => '起跑线 学英语',
    'description' => '学校的大门，像是一把重新丈量这个社会的尺子。那些来自形形色色的，或富有、或贫穷家庭的孩子们，迈进那道大门，穿上清一色校服，一切便清',
    'posids' => '1',
    'url' => 'https://www.tianliangedu.com/index.php?m=content&c=index&a=show&catid=16&id=3',
    'listorder' => '3',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'tianliangedu',
    'inputtime' => '1499324405',
    'updatetime' => '1499325862',
    'hitsid' => 'c-13-10',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  11 => 
  array (
    'id' => '11',
    'catid' => '21',
    'typeid' => '0',
    'title' => '武汉市新一轮学前教育保教实验送教下乡走进江夏区',
    'style' => '',
    'thumb' => 'https://www.tianliangedu.com/uploadfile/2017/0706/20170706052258723.jpg',
    'keywords' => '江夏区 武汉市 一轮',
    'description' => '国家学前教育改革发展实验区“健全学前教育教研制度”暨武汉市新一轮学前教育保教实验送教下乡走进江夏区',
    'posids' => '0',
    'url' => 'https://www.tianliangedu.com/2017/latest_0706/11.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'tianliangedu',
    'inputtime' => '1499332902',
    'updatetime' => '1499332978',
    'hitsid' => 'c-13-11',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  16 => 
  array (
    'id' => '16',
    'catid' => '21',
    'typeid' => '0',
    'title' => '俞敏洪：互联网有速度，教育要有温度',
    'style' => '',
    'thumb' => 'https://www.tianliangedu.com/uploadfile/2017/0713/20170713121807876.jpg',
    'keywords' => '天亮教育 教育温度 互联网',
    'description' => '所谓的速度与温度并存，我们互联网要速度，但是我们要做温度。做有温度的教育，需要我们共同努力。',
    'posids' => '1',
    'url' => 'https://www.tianliangedu.com/2017/latest_0713/16.html',
    'listorder' => '4',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'tianliangedu',
    'inputtime' => '1499919426',
    'updatetime' => '1499919564',
    'hitsid' => 'c-13-16',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  21 => 
  array (
    'id' => '21',
    'catid' => '21',
    'typeid' => '0',
    'title' => '这个东西比钱重要！“95后”找工作不看待遇只看它',
    'style' => '',
    'thumb' => 'https://www.tianliangedu.com/uploadfile/2017/0718/20170718025322130.jpg',
    'keywords' => '找工作 待遇 天亮教育',
    'description' => '天亮教育发布，前几年，90后大量步入社会；而现在，95后也开始逐渐走出象牙塔。然而，与70、80后的毕业生们不同，95后已不再将工作待遇看成是最重要的求职指标。',
    'posids' => '1',
    'url' => 'https://www.tianliangedu.com/2017/latest_0718/21.html',
    'listorder' => '5',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1500360659',
    'updatetime' => '1500360802',
    'hitsid' => 'c-13-21',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  9 => 
  array (
    'id' => '9',
    'catid' => '21',
    'typeid' => '0',
    'title' => '天亮教育呼吁学生去省博物馆感受文化暑假',
    'style' => '',
    'thumb' => 'https://www.tianliangedu.com/uploadfile/2017/0706/20170706023412394.jpg',
    'keywords' => '天亮培优学校 博物馆 小学生',
    'description' => '我省各大博物为中小学生准备了内容丰富的系列文化大餐，天亮培优学校呼吁学生去湖北省博物馆，“穿越时空”回到汉唐，跟专业人士学古代“六艺”，感受文化暑假。',
    'posids' => '0',
    'url' => 'https://www.tianliangedu.com/index.php?m=content&c=index&a=show&catid=16&id=1',
    'listorder' => '1',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'phpcms',
    'inputtime' => '1497945682',
    'updatetime' => '1499325045',
    'hitsid' => 'c-13-9',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>