<?php
return array (
  5 => 
  array (
    'id' => '5',
    'catid' => '18',
    'typeid' => '0',
    'title' => '魔方玩得好不好与智商有关吗？',
    'style' => '',
    'thumb' => 'http://www.tianliangedu.com/uploadfile/2017/0706/20170706035516979.jpg',
    'keywords' => '魔方 智商 天亮',
    'description' => '魔方玩得好不好与智商有关吗？ 发明人告诉你：NO！',
    'posids' => '0',
    'url' => 'http://www.tianliangedu.com/2017/gaozhong_0620/5.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1497950357',
    'updatetime' => '1498050251',
    'hitsid' => 'c-13-5',
    'views' => '6',
    'yesterdayviews' => '3',
    'dayviews' => '3',
    'weekviews' => '6',
    'monthviews' => '6',
  ),
  13 => 
  array (
    'id' => '13',
    'catid' => '18',
    'typeid' => '0',
    'title' => '最好的教育其实就在身边',
    'style' => '',
    'thumb' => '',
    'keywords' => '教育 辅导 天亮培优',
    'description' => '众里寻他千百度，蓦然回首，那人却在，灯火阑珊处。细品辛弃疾的《青玉案·元夕》，会领悟一个小哲理，那就是我们苦苦寻找的答案，往往就在身边。',
    'posids' => '1',
    'url' => 'http://www.tianliangedu.com/2017/gaozhong_0710/13.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'tianliangedu',
    'inputtime' => '1499657421',
    'updatetime' => '1499657741',
    'hitsid' => 'c-13-13',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  14 => 
  array (
    'id' => '14',
    'catid' => '18',
    'typeid' => '0',
    'title' => '毕业致辞官话少了段子多了，需读取其中的人生密码',
    'style' => '',
    'thumb' => '',
    'keywords' => '毕业 人生密码 天亮教育',
    'description' => '  又到毕业季，很多人要告别熟悉的校园，少不了会有些离愁别绪。出发前，聆听毕业典礼上的简短致辞，成了毕业生们学成下山前的必备行囊，',
    'posids' => '0',
    'url' => 'http://www.tianliangedu.com/2017/gaozhong_0710/14.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'tianliangedu',
    'inputtime' => '1499658419',
    'updatetime' => '1499658562',
    'hitsid' => 'c-13-14',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  18 => 
  array (
    'id' => '18',
    'catid' => '18',
    'typeid' => '0',
    'title' => '奥巴马女儿要上哈佛了！忙，也给孩子最优质的陪伴',
    'style' => '',
    'thumb' => 'http://www.tianliangedu.com/uploadfile/2017/0713/20170713013349639.jpg',
    'keywords' => '哈佛 奥巴马 全世界',
    'description' => '前美国第一千金，奥巴马的大女儿玛利亚·奥巴马马上要跟随老爸老妈的脚步，入学哈佛了。',
    'posids' => '1',
    'url' => 'http://www.tianliangedu.com/2017/gaozhong_0713/18.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'tianliangedu',
    'inputtime' => '1499923698',
    'updatetime' => '1499924029',
    'hitsid' => 'c-13-18',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  8 => 
  array (
    'id' => '8',
    'catid' => '18',
    'typeid' => '0',
    'title' => '警惕七种高考招生骗局',
    'style' => '',
    'thumb' => '',
    'keywords' => '高考招生 骗局',
    'description' => '天亮培优学校温馨提示，招生录取期间，不法分子打着种种幌子进行招生诈骗，在此提醒广大家长和考生，注意识别招生骗子的诈骗伎俩。',
    'posids' => '1',
    'url' => 'http://www.tianliangedu.com/2017/gaozhong_0706/8.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'tianliangedu',
    'inputtime' => '1499322240',
    'updatetime' => '1499322333',
    'hitsid' => 'c-13-8',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>