<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '20',
    'typeid' => '0',
    'title' => '武汉天亮培优学校官方网站上线',
    'style' => '',
    'thumb' => '',
    'keywords' => '武汉天亮 培优学校 天亮官网',
    'description' => '热烈庆祝武汉天亮培优学校，官方网站（http:  www tianliangedu com）正式上线',
    'posids' => '1',
    'url' => 'https://www.tianliangedu.com/2017/poster_0619/1.html',
    'listorder' => '3',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1497856328',
    'updatetime' => '1498034684',
    'hitsid' => 'c-13-1',
    'views' => '34',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '34',
    'monthviews' => '34',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '20',
    'typeid' => '0',
    'title' => '武汉市教育事业发展“十三五”规划',
    'style' => '',
    'thumb' => '',
    'keywords' => '武汉 教育 发展 十三五 规划',
    'description' => '武汉天亮教育转武汉市教育事业发展“十三五”规划，“十三五”是我市率先全面建成小康社会，打造经济、城市、民生三个“升级版”的关键时期。',
    'posids' => '1',
    'url' => 'https://www.tianliangedu.com/2017/poster_0620/2.html',
    'listorder' => '2',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1497947938',
    'updatetime' => '1498056503',
    'hitsid' => 'c-13-2',
    'views' => '5',
    'yesterdayviews' => '2',
    'dayviews' => '3',
    'weekviews' => '5',
    'monthviews' => '5',
  ),
  12 => 
  array (
    'id' => '12',
    'catid' => '20',
    'typeid' => '0',
    'title' => '2017年武汉市职业教育与成人教育工作要点',
    'style' => '',
    'thumb' => '',
    'keywords' => '武汉市 成人教育 职业教育',
    'description' => '武汉天亮教育转2017年全市职业教育与成人教育工作总体要求，响应国家“创新改革、内涵发展、巩固规模、提高质量”的现代化教育思路。',
    'posids' => '1',
    'url' => 'https://www.tianliangedu.com/2017/poster_0710/12.html',
    'listorder' => '1',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'tianliangedu',
    'inputtime' => '1499656527',
    'updatetime' => '1499656682',
    'hitsid' => 'c-13-12',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>