import key from './../key';

export const TOGGLE_VIEW_TASK_ITEM = `${key}/TOGGLE_VIEW_TASK_ITEM`;

export const SET_VIEW_TASK_ITEM_TARGET = `${key}/SET_VIEW_TASK_ITEM_TARGET`;

export const REQUEST_VIEW_TASK_ITEM_DETAIL = `${key}/REQUEST_VIEW_TASK_ITEM_DETAIL`;
export const RECEIVE_VIEW_TASK_ITEM_DETAIL = `${key}/RECEIVE_VIEW_TASK_ITEM_DETAIL`;

export const SET_VIEW_TASK_ITEM_PAGE = `${key}/SET_VIEW_TASK_ITEM_PAGE`;
