export const REQUEST_PRINTERS = 'App/REQUEST_PRINTERS';
export const RECEIVE_PRINTERS = 'App/RECEIVE_PRINTERS';
export const ERROR_PRINTERS = 'App/ERROR_PRINTERS';

export const SET_PRINTERS_CURRENT = 'App/SET_PRINTERS_CURRENT';

export const REQUEST_PRINTERS_ITEM = 'App/REQUEST_PRINTERS_ITEM';
export const RECEIVE_PRINTERS_ITEM = 'App/RECEIVE_PRINTERS_ITEM';
